
import React from 'react';
import { Metadata } from 'next';
import { generateEtymology } from '@/lib/cledor';
import { getCachedWord, saveWordToCache } from '@/lib/store';
import ResultsDashboard from '@/app/components/ResultsDashboard';
import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import LanguageToggle from '@/app/components/LanguageToggle';
import Header from '@/app/components/Header';

interface PageProps {
    params: Promise<{
        slug: string;
    }>
}

// 1. Dynamic Metadata for SEO
export async function generateMetadata(props: PageProps): Promise<Metadata> {
    const params = await props.params;
    const term = params.slug.replace(/-/g, ' ');
    // We try to get from cache first for metadata, otherwise we fallback to generic
    // (We avoid generating FULL heavy data just for metadata if not cached to save speed/cost)
    const cached = await getCachedWord(term);

    const title = cached
        ? `Etymology of ${cached.etymology.meta.word} - Le Mot Clef`
        : `Etymology of ${term} - Le Mot Clef`;

    const description = cached
        ? cached.etymology.semantic_soul.description
        : `Discover the hidden history and visual origins of the French word "${term}".`;

    return {
        title: title,
        description: description,
        openGraph: {
            title: title,
            description: description,
            images: cached?.etymology.image_url ? [cached.etymology.image_url] : [],
        }
    };
}

export default async function WordPage(props: PageProps) {
    const params = await props.params;
    const term = params.slug.replace(/-/g, ' ');

    let data;

    // A. Check Cache
    const cached = await getCachedWord(term);

    if (cached) {
        console.log(`[SSR] Cache hit for ${term}`);
        data = cached.etymology;
    } else {
        // B. Generate on Server (Cold Start)
        console.log(`[SSR] Cache miss for ${term}. Generating...`);
        try {
            data = await generateEtymology(term);
            // Save to cache for next time
            await saveWordToCache(term, data);
        } catch (error) {
            console.error("SSR Generation Failed", error);
            return (
                <div className="min-h-screen flex items-center justify-center bg-slate-900 text-slate-400">
                    <div className="text-center p-8 border border-red-900/50 bg-red-900/10 rounded-xl">
                        <h1 className="text-2xl font-bold text-red-400 mb-2">Analysis Failed</h1>
                        <p>Our etymologists could not uncover this word right now.</p>
                        <Link href="/" className="mt-6 inline-block text-sm underline hover:text-white">Return Home</Link>
                    </div>
                </div>
            );
        }
    }

    // JSON-LD for Schema.org (DefinedTerm)
    const jsonLd = {
        '@context': 'https://schema.org',
        '@type': 'DefinedTerm',
        'name': data.meta.word,
        'description': data.semantic_soul.description,
        'inDefinedTermSet': {
            '@type': 'DefinedTermSet',
            'name': 'Le Mot Clef Visual Dictionary',
            'url': 'https://le-mot-clef.com'
        },
        'termCode': data.meta.word.toLowerCase()
    };

    return (
        <main className="min-h-screen text-text-primary flex flex-col font-sans">
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
            />
            {/* Sticky Nav for deep pages */}
            <Header variant="sticky" backLink={{ href: '/', type: 'search' }} />

            <div className="flex-grow">
                <ResultsDashboard data={data} />
            </div>

            {/* SEO Footnote */}
            <footer className="p-8 text-center text-slate-600 text-xs border-t border-slate-800 mt-12 bg-slate-950">
                <p>Generated by Le Mot Clef AI Engine. Checked by Cora (Visual Archivist) and Cledor (Etymologist).</p>
                <div className="mt-2 flex justify-center gap-4">
                    <Link href="/" className="hover:text-slate-400">Search Another Word</Link>
                    <span>•</span>
                    <Link href="/mot/amour" className="hover:text-slate-400">Amour</Link>
                    <Link href="/mot/travail" className="hover:text-slate-400">Travail</Link>
                    <Link href="/mot/liberte" className="hover:text-slate-400">Liberté</Link>
                </div>
            </footer>
        </main>
    );
}
